replicaCount: 2

image:
  repository: nginx
  tag: latest

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: true
  className: haproxy

  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix

  annotations:
    haproxy.org/path-rewrite: /
