replicaCount: 2

image:
  repository: nginx
  tag: latest

service:
  type: ClusterIP
  port: 80

serviceAccount:
  create: true
  name: ""

httpRoute:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi


ingress:
  enabled: true
  className: nginx

  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
